checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: ../checkpoints/1b/order_matters
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false
data_stages:
- data: 
    dataset:
      - name: ../grouped_dataset/fineweb-100BT/train/0
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train/1
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train/2
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train/3
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train/4
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train/5
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train/6
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train/7
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train-2/8
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train-2/9
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train-2/10
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train-2/11
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train-2/12
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train-2/13
        prob: 0.0666
      - name: ../grouped_dataset/fineweb-100BT/train-2/14
        prob: 0.0666
    seed: 42
  name: Stable Training Stage
  start_training_step: 1
- data:
    dataset:
      - name: ../grouped_dataset/fineweb-100BT/train/0
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train/1
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train/2
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train/3
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train/4
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train/5
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train/6
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train/7
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train-2/8
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train-2/9
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train-2/10
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train-2/11
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train-2/12
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train-2/13
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-100BT/train-2/14
        prob: 0.0508
      - name: ../grouped_dataset/fineweb-2-ko-2.2B
        prob: 0.237
    seed: 42
  name: Multilingual training
  start_training_step: 8073
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: debug
  run: smollm_qwen_20250603_104600_local
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
metrics_logging: null
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    scaling_method: NUM_LAYERS
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    attention_bias: false
    bos_token_id: 151643
    eos_token_id: 151645
    hidden_act: silu
    hidden_size: 2048
    initializer_range: 0.02
    intermediate_size: 8192
    is_llama_config: true
    max_position_embeddings: 2048
    num_attention_heads: 32
    num_hidden_layers: 16
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 500000
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 151936
    z_loss_coefficient: 0.0001
    z_loss_enabled: false
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0005
    lr_warmup_steps: 250
    lr_warmup_style: linear
    lr_decay_starting_step: 11250
    lr_decay_style: linear
    min_decay_lr: 0.0
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  weight_decay_exclude_named_params: []
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 4
  expert_parallel_size: 1
  moe_layer_recompute: false
  pp: 2
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: Qwen/Qwen3-8B
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 64
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 4
  sequence_length: 2048
  train_steps: 12500
  val_check_interval: -1
